### ISSUE TITLE
About the k600 model config

### ISSUE THREAD

**Issue by bolin-chen** [Sense-X/UniFormer#2]
In `https://github.com/Sense-X/UniFormer/blob/main/video_classification/exp/uniformer_b32x4_k600/config.yaml `

```
MODEL:
  NUM_CLASSES: 400
  ARCH: uniformer
  MODEL_NAME: Uniformer
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
```

It seems that the NUM_CLASSES should be 600 instead of 400. Other k600 config files have the same problem. Or are the config files themselves wrong?
