### ISSUE TITLE
ssv1测试准确率下降

### ISSUE THREAD

**Issue by ZQhaha** [Sense-X/UniFormer#82]
作者，你好！
非常感谢您的工作！但是我在用您提供的pth复现ssv1的实验结果时，发现准确率总会低1%-2%。例如，我在运行uniformer_s16_sthv1_prek600/test.sh 时，得到的top-1只有52.0（crop = 1），而您文中报告的是54.4，这让我感到有些困惑。我不知道是不是我写的test.sh的有问题，希望得到您的帮助。以下是我复现时使用的tesh.sh，test.yaml和stdout.log。

- test.sh

```shell
work_path=$(dirname $0)
PYTHONPATH=$PYTHONPATH:./slowfast \
python tools/run_net.py \
  --cfg $work_path/test.yaml \
  DATA.PATH_TO_DATA_DIR ./data_list/sthv1 \
  DATA.PATH_PREFIX /data/mydreany/zq_unss/ssv1 \
  DATA.PATH_LABEL_SEPARATOR "," \
  TRAIN.EVAL_PERIOD 5 \
  TRAIN.CHECKPOINT_PERIOD 1 \
  TRAIN.BATCH_SIZE 32 \
  NUM_GPUS 1 \
  UNIFORMER.DROP_DEPTH_RATE 0.2 \
  SOLVER.MAX_EPOCH 60 \
  SOLVER.BASE_LR 2e-4 \
  SOLVER.WARMUP_EPOCHS 5.0 \
  DATA.TEST_CROP_SIZE 224 \
  TEST.NUM_ENSEMBLE_VIEWS 1 \
  TEST.NUM_SPATIAL_CROPS 1 \
  TRAIN.ENABLE False \
  TEST.CHECKPOINT_FILE_PATH /model/mydreany/uniformer_model/checkpoint_pth/uniformer_small_sthv1_16_prek600.pth \
  OUTPUT_DIR /output
```

- test.yaml

```yaml
TRAIN:
  ENABLE: True
  DATASET: sth
  BATCH_SIZE: 8
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  RANDOM_FLIP: False
  TRAIN_JITTER_SCALES: [224, 224]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  # PATH_TO_DATA_DIR: path-to-imagenet-dir
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
UNIFORMER:
  EMBED_DIM: [64, 128, 320, 512]
  DEPTH: [3, 4, 8, 3]
  HEAD_DIM: 64
  MLP_RATIO: 4
  DROPOUT_RATE: 0
  ATTENTION_DROPOUT_RATE: 0
  DROP_DEPTH_RATE: 0.1
  SPLIT: False
  PRETRAIN_NAME: 'uniformer_small_k600_16x4'
AUG:
  NUM_SAMPLE: 2
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 30.0
  LR_POLICY: cosine
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
MODEL:
  NUM_CLASSES: 174
  ARCH: uniformer
  MODEL_NAME: Uniformer
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: sth
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .


```

- [stdout.log](https://github.com/Sense-X/UniFormer/files/9791688/stdout.log)
